const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.3,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "images/shirt2.jpg",
      price: 75,
      brand: "Addias",
      rating: 4.0,
      numReviews: 7,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "images/shirt3.jpg",
      price: 63,
      brand: "Raymond",
      rating: 3.8,
      numReviews: 5,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-shirt",
      category: "Shirts",
      image: "images/pants1.jpg",
      price: 90,
      brand: "Apple Bottoms",
      rating: 2.8,
      numReviews: 15,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.2,
      numReviews: 11,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.2,
      numReviews: 13,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};

export default data;
